#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, ast, zlib

DATA_SIZE = 1375

# Class for the sender
class Sender:
	# Initialize connection and global variables
	def __init__(self, host, port):
		self.host = host
		self.remote_port = int(port)
		self.log("Sender starting up using port %s" % self.remote_port)
		self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
		self.socket.bind(('0.0.0.0', 0))
		self.waiting = False
		self.all_msg = []
		self.to_send = []
		self.packets_in_transit = []
		self.sequence_num = 0
		self.sequences_sent = []
		self.RTT = 1
		self.RTT_alpha = 0.875
		self.RTO = 2
		self.window = 4
		self.ssthresh = 16
	


	# Log the given message to stderr
	def log(self, message):
		sys.stderr.write(message + "\n")
		sys.stderr.flush()


	# Send the given message to receiver
	def send(self, message):
		self.socket.sendto(json.dumps(message).encode('utf-8'), (self.host, self.remote_port))


	# Parse messages to send from standard input
	def get_data(self):
		while True:
			data = sys.stdin.read(DATA_SIZE)
			if len(data) == 0:
				# Stop receiving input when there is no more data to read
				break;
			else:
				# Format the message and append to to_send list, and keep a copy in all_msg list
				msg = {"type": "msg", "data": data, "seq": self.sequence_num, "timesent": 0, "checksum": 0}
				self.sequence_num += 1
				checksum = json.dumps({"data": msg["data"]}).encode('utf-8')
				msg["checksum"] = zlib.crc32(checksum)
				self.to_send.append(msg)
				self.all_msg.append(msg)
				self.log("ALL DATA TO SEND: " + str(self.to_send))


	# Check if the given received message is corrupt
	def check_corrupt(self, msg):
		for packet in self.all_msg:
			if (("seq" in list(msg.keys())) and ("type" in list(msg.keys())) and ("data" in list(msg.keys()))):
				if (msg["seq"] == packet["seq"]):
					if (msg["type"] == "ack"):
						if (msg["data"] == packet["data"]):
							return False
			else:
				continue
		return True


	# Parse response from receiver
	def response(self, k):
		msg = k.decode('utf-8')
		corrupt = False
		try:
			msg = json.loads(msg)
		except:
			corrupt = True
		# If message was corrupt resend the packet
		if (corrupt or self.check_corrupt(msg)):
			self.log("RECIEVED CORRUPT ACK OF SEQUENCE: " + str(msg["seq"]))
			for packet in self.all_msg:
				if (packet["seq"] == msg["seq"]):
					packet["timesent"] = time.time()
					self.log("RESENDING CORRUPT PACKET OF SEQUENCE: " + str(msg["seq"]))
					self.send(packet)
		else:
			self.log("RECIEVED ACK OF SEQUENCE: " + str(msg["seq"]))
			# Remove received packet from list of packets_in_transit
			for packet in self.packets_in_transit:
				if (msg["seq"] == packet["seq"]):
					# Calculate new RTT and RTO
					new_sample = time.time() - packet["timesent"]
					new_RTT = (self.RTT_alpha * (self.RTT / 1000)) + ((1 - self.RTT_alpha) * new_sample / 1000)
					self.RTT = self.RTT - new_RTT
					self.RTO = self.RTT * 2
					self.log("CALCULATED NEW RTT TO BE: " + str(self.RTT) + " AND NEW RTO TO BE: " + str(self.RTO))
					self.window += 1

					# Adjust window size
					#if (self.window < self.ssthresh):
						# slow start implementation
					#	self.window += 1
					#else:
						# congestion avoidance implementation
						#self.window = int((self.window + 1) / self.window)
					self.log("READJUSTED WINDOW TO BE OF SIZE: " + str(self.window))
						
					self.packets_in_transit.remove(packet)
		self.waiting = False

		# If there are no packets left to send, exit
		if (len(self.packets_in_transit) == 0):
			self.log("All done!")
			sys.exit(0)


	# Resend packets if they have exceeded the RTT without an ACK (have been dropped)
	def dropped(self):
		for packet in self.packets_in_transit:
			current = time.time()
			# If the packet has exceeded RTO
			if (current > packet["timesent"] + self.RTO):
				# Multiplicative decrease for congestion
				#self.ssthresh = math.ceil(self.window / 2)
				self.window = math.ceil(self.window / 2)
				self.log("READJUSTED WINDOW TO BE SIZE: " + str(self.window) + " AND NEW SSTHRESH TO BE: " + str(self.ssthresh))

				# Resend the packet
				packet["timesent"] = time.time()
				checksum = json.dumps({"data": packet["data"]}).encode('utf-8')
				packet["checksum"] = zlib.crc32(checksum)
				self.log("PACKET EXCEEDED RTO, RESENDING PACKET OF SEQUENCE: " +  str(packet["seq"]))
				self.send(packet)


	# Send more packets if it does not exceed the window
	def send_more(self):
		while ((len(self.packets_in_transit) < self.window) and (len(self.to_send) >= 1)):
			# If the packet is not a duplicate
			if not(self.to_send[0]["seq"] in self.sequences_sent):
				self.log("SENDING MESSAGE OF SEQUENCE: " + str(self.to_send[0]["seq"]))
				self.to_send[0]["timesent"] = time.time()
				self.send(self.to_send[0])
				self.sequences_sent.append(self.to_send[0]["seq"])
				self.packets_in_transit.append(self.to_send[0])
				del self.to_send[0]
			else:
				self.to_send.remove(self.to_send[self.packets_in_transit])
			self.waiting = True


	def run(self):
		# Get all messages to be sent
		self.get_data()
		
		while True:
			sockets = [self.socket, sys.stdin] if not self.waiting else [self.socket]
			socks = select.select(sockets, [], [], 0.1)[0]
			for conn in socks:
				# Receive data from receiver
				if conn == self.socket:
					k, addr = conn.recvfrom(65535)
					self.response(k)

				# Receive data from standard input
				elif conn == sys.stdin:
					self.dropped()
					self.send_more()
		return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()
